title: Wallpapers
filename: README.md
description: "Just a rather overengineered wallpaper repository :) \n\nWhy? \n\n**R:** Why not? Also, I was bored"
sections:
    automations:
        title: Automations
        info: "![Update all README.md](https://github.com/gustavodiel/wallpapers/workflows/Update%20all%20README.md/badge.svg)"
    contribute:
        title: Contributing
        info: "All wallppers are welcome (except NSFW :eyes:)! Always remember to try and check the source and update the README ;)
        \n\nAlso, if you know the source of any wallpaper, please enlighten us!"
    usage:
        title: Usage
        info: "Adding a new wallpaper:\n
        - Place your image (preferably .png or .jpg) inside the correct folder, based on it's aspect ratio (or create a new one if it makes sense)\n
        - Run `python create_missing_yml.py` (see [requirements.txt](requirements.txt)]) and fill in the information on the generated files\n
        - (optional) Run `python create_readme.py` in order to see the final rendered Readme. This is optional because this repo includes a Github action that automatically runs this script\n
        - - This script will also generate a thumbnail image so that the front page is faster to load"
