title: Wallpapers
filename: README.md
description: "Just a rather overengineered wallpaper repository :) \n\nWhy? \n\n**R:** Why not? Also, I was bored"
sections:
    automations:
        title: Automations
        info: "![Update all README.md](https://github.com/gustavodiel/wallpapers/workflows/Update%20all%20README.md/badge.svg)"
    contribute:
        title: Contributing
        info: "All wallppers are welcome (except NSFW :eyes:)! Always remember to try and check the source and update the README ;)
            \n\nAlso, when you place your images, run `python create_missing_yml.py` (requires Pillow) and fill in the information on the generated files. After that, run `python create_readme.py` (requires pyyaml) and commit.
            \n\nAlso also, if you know the source of any wallpaper, please enlighten us!"
